{% set name = "google-cloud-aiplatform" %}
{% set version = "1.63.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-aiplatform-{{ version }}.tar.gz
  sha256: 4eb2398bed02a60ad23656b4a442b5d6efa181d11653f8c31f0a5f642c09f913

build:
  entry_points:
    - tb-gcp-uploader=google.cloud.aiplatform.tensorboard.uploader_main:run_main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - google-api-core >=1.34.1,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*
    - google-api-core-grpc
    - proto-plus >=1.22.3,<2.0.0dev
    - protobuf >=3.20.2,<6.0.0dev,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5
    - packaging >=14.3
    - google-auth >=2.14.1,<3.0.0dev
    - google-cloud-storage >=1.32.0,<3.0.0dev
    - google-cloud-bigquery-core >=1.15.0,<4.0.0dev,!=3.20.0
    - google-cloud-resource-manager >=1.3.3,<3.0.0dev
    - shapely <3.0.0dev
    - docstring_parser <1
    - pydantic <3

test:
  imports:
    - google
    # vertex_ray is an extra and shouldn't be tested unless we want to add those extras
    # - vertex_ray
    - vertexai
  commands:
    - pip check
    # missing dependency on absl-py
    # - tb-gcp-uploader --help
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-aiplatform
  summary: Vertex AI API client library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
