{% set name = "google-cloud-aiplatform" %}
{% set version = "1.121.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/google_cloud_aiplatform-{{ version }}.tar.gz
  sha256: 65710396238fa461dbea9b2af9ed23f95458d70d9684e75519c7c9c1601ff308

build:
  entry_points:
    - tb-gcp-uploader=google.cloud.aiplatform.tensorboard.uploader_main:run_main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - google-api-core >=1.34.1,<3.0.0,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*
    - google-api-core-grpc
    - google-auth >=2.14.1,<3.0.0
    - proto-plus >=1.22.3,<2.0.0
    - protobuf >=3.20.2,<7.0.0,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5
    - packaging >=14.3
    - google-cloud-storage >=1.32.0,<3.0.0
    - google-cloud-bigquery-core >=1.15.0,<4.0.0,!=3.20.0
    - google-cloud-resource-manager >=1.3.3,<3.0.0
    - shapely <3.0.0
    - google-genai >=1.37.0,<2.0.0
    # genai_requires
    - pydantic <3
    - typing_extensions
    - docstring_parser <1

test:
  imports:
    - google
    # vertex_ray is an extra and shouldn't be tested unless we want to add those extras
    # - vertex_ray
    - vertexai
  commands:
    - pip check
    # missing dependency on absl-py
    # - tb-gcp-uploader --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/googleapis/python-aiplatform
  summary: Vertex AI API client library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
